=== h3rm3x/DAM/Primero/LMSGI/UD4 XML/EXAMEN_XSD/EX_6/ex6.dtd
<!ELEMENT concesionario (modelo+)>
<!ELEMENT modelo (#PCDATA| motor| potencia| consumo_medio)*>
<!-- atributos modelo-->
<!ATTLIST modelo id ID #REQUIRED>
<!ATTLIST modelo modelos_relacionados IDREFS #IMPLIED>
<!-- definicion hijos modelo -->
<!ELEMENT motor (#PCDATA)>
<!ATTLIST motor modelos_relacionados IDREF #IMPLIED>
<!ELEMENT potencia (#PCDATA)>
<!ELEMENT consumo_medio (#PCDATA)>
<!ATTLIST consumo_medio velocidad_km CDATA #REQUIRED>
<!ATTLIST consumo_medio modelo_relaionado IDREFS #IMPLIED>

=== h3rm3x/DAM/LMSGI/UD4 XML/EXAMEN_XSD/EX_6/ejercicio6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE concesionario SYSTEM "ex6.dtd">
<concesionario>
	<modelo id="Modelo556">No disponible</modelo>

	<modelo id="Modelo555" modelos_relacionados="Modelo444 Modelo556">
		Este modelo tiene un 
		<motor modelos_relacionados="Modelo556">1.998cc 16v. de cuatro cilindros</motor> que desarrolla una potencia de 
		<potencia>128</potencia> CV. Dispone de cambio manual ... el consumo medio de este monovolumen es 
		<consumo_medio velocidad_km="100">11</consumo_medio> 
		a los 100 km. El precio base es de 2.225.000.
	</modelo>
	<modelo id="Modelo557">No disponible</modelo>

	<modelo id="Modelo154">No disponible</modelo>

	<modelo id="Modelo444" modelos_relacionados="Modelo555 Modelo154">
		Este modelo tiene un 
		<motor modelos_relacionados="Modelo556">2.000cc 16v. de cuatro cilindros</motor> con 
		<potencia>128</potencia> CV. Dispone de cambio manual ... el consumo medio de este monovolumen es 
		<consumo_medio velocidad_km="100">11</consumo_medio> a los 100 km. El precio base es de 2.500.000.
	</modelo>
</concesionario>
