=== h3rm3x/DAM/Primero/LMSGI/UD4 XML/Ejercicios_XSD/ejercicio factura/factura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="factura">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="encabezado">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fecha">
                                <xs:complexType>
                                    <xs:attribute name="dia" type="dia"/>
                                    <xs:attribute name="mes" type="mes"/>
                                    <xs:attribute name="año" type="año"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="info_cliente">
                                <xs:complexType>
                                    <xs:attribute name="nombre_fiscal" type="xs:string"/>
                                    <xs:attribute name="NIF" type="xs:string"/>
                                    <xs:attribute name="nombre_comercial" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="info_proveedor">
                                <xs:complexType>
                                    <xs:attribute name="nombre_fiscal" type="xs:string"/>
                                    <xs:attribute name="NIF" type="xs:string" use="required"/>
                                    <xs:attribute name="nombre_comercial" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id_factura" type="xs:ID" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="linea" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="articulo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="descripcion" type="xs:string"/>
                                        <xs:element name="precio_sin_iva" type="xs:decimal"/>
                                        <xs:element name="precio_con_iva">
                                        <xs:complexType>
                                            <xs:simpleContent>
                                                <xs:extension base="xs:decimal">
                                                    <xs:attribute name="tipo_iva" type="tipo_iva" use="required"/>
                                                </xs:extension>
                                            </xs:simpleContent>
                                        </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id_articulo" type="xs:ID"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="num_unidades" type="xs:positiveInteger"/>
                            <xs:element name="importe_total" type="xs:decimal"/>
                        </xs:sequence>
                        <xs:attribute name="id_linea" type="xs:ID"/>
                        <xs:attribute name="articulo_ref" type="xs:IDREF"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="resumen_total">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="subtotal" >
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="con_iva_4" type="xs:decimal" minOccurs="0"/>
                                        <xs:element name="con_iva_10" type="xs:decimal" minOccurs="0"/>
                                        <xs:element name="con_iva_21" type="xs:decimal" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="total_sin_iva" type="xs:decimal"/>
                            <xs:element name="total_con_iva" type="xs:decimal"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="tipo_iva">
        <xs:restriction base="xs:integer">
            <xs:enumeration value="4"/>
            <xs:enumeration value="10"/>
            <xs:enumeration value="21"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="dia">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="31"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="mes">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="12"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="año">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1900"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== h3rm3x/DAM/LMSGI/UD4/Ejercicios_XSD/ejercicio factura/factura.xml
<?xml version="1.0" encoding="UTF-8"?>
<factura
    xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="factura.xsd">
    <encabezado id_factura="A123">
        <fecha dia="11" mes="3" aÃ±o="2025" />
        <info_cliente nombre_fiscal="Nombre1" NIF="12345678A" nombre_comercial="nombre comercial 1"/>
        <info_proveedor nombre_fiscal="Nombre2" NIF="12345679B" nombre_comercial="Nombre comercial 2"/>
    </encabezado>
    
    <linea id_linea="B123" articulo_ref="C12">
        <articulo id_articulo="C12">
            <descripcion>Descripcion del articulo</descripcion>
            <precio_sin_iva>100</precio_sin_iva>
            <precio_con_iva tipo_iva="4">104</precio_con_iva>
        </articulo>
        <num_unidades></num_unidades>
        <importe_total></importe_total>
            
    </linea>
    <resumen_total>
        <subtotal>
            <con_iva_4>200</con_iva_4>
            <con_iva_10></con_iva_10>
            <con_iva_21></con_iva_21>
        </subtotal>
        <total_sin_iva></total_sin_iva>
        <total_con_iva></total_con_iva>
    </resumen_total>
</factura>

=== h3rm3x/DAM/LMSGI/UD4 XML/Ejercicios_XSD/ejercicio factura/factura.xml
<?xml version="1.0" encoding="UTF-8"?>
<factura
    xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="factura.xsd">
    <encabezado id_factura="A123">
        <fecha dia="11" mes="3" aÃ±o="2025" />
        <info_cliente nombre_fiscal="Nombre1" NIF="12345678A" nombre_comercial="nombre comercial 1"/>
        <info_proveedor nombre_fiscal="Nombre2" NIF="12345679B" nombre_comercial="Nombre comercial 2"/>
    </encabezado>
    
    <linea id_linea="B123" articulo_ref="C12">
        <articulo id_articulo="C12">
            <descripcion>Descripcion del articulo</descripcion>
            <precio_sin_iva>100</precio_sin_iva>
            <precio_con_iva tipo_iva="4">104</precio_con_iva>
        </articulo>
        <num_unidades>10</num_unidades>
        <importe_total>1040</importe_total>
            
    </linea>
    <linea id_linea="B124" articulo_ref="A22">
        <articulo id_articulo="A22">
            <descripcion>Descripcion del articulo</descripcion>
            <precio_sin_iva>80</precio_sin_iva>
            <precio_con_iva tipo_iva="21">96.8</precio_con_iva>
        </articulo>
        <num_unidades>5</num_unidades>
        <importe_total>484</importe_total>
            
    </linea>
    <resumen_total>
        <subtotal>
            <con_iva_4>1040.00</con_iva_4>
            <con_iva_10>0.00</con_iva_10>
            <con_iva_21>484.00</con_iva_21>
        </subtotal>
        <total_sin_iva>1400.00</total_sin_iva>
        <total_con_iva>1524.00</total_con_iva>
    </resumen_total>
</factura>
