=== h3rm3x/DAM/LMSGI/UD4/Ejercicios_XSD/pack_5/EX_5_3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="subasta">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="productos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="producto" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="propietario" type="xs:string"/>
                                        <xs:element name="precio" type="dec"/>
                                        <xs:element name="precio_min" type="dec" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:simpleType name="dec">
        <xs:restriction base="xs:decimal">
            <xs:maxExclusive value="10000.00"/>
            <xs:totalDigits value="6"></xs:totalDigits>
            <xs:fractionDigits value="2"></xs:fractionDigits>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== h3rm3x/DAM/LMSGI/UD4/Ejercicios_XSD/pack_5/ex_5_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="ex_5_3.xsd" type="application/xml-schema"?>
<subasta xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="ex_5_3.xsd">
    <productos>
        <producto>
            <propietario>Pepe</propietario>
            <precio>1000.00</precio>
        </producto>
        <producto>
            <propietario>Manolo</propietario>
            <precio>200.00</precio>
            <precio_min>110.00</precio_min>
        </producto>
    </productos>
</subasta>
