=== h3rm3x/DAM/LMSGI/UD4/EXAMEN_XSD/EX_7/ejercicio7.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="datos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="agrupacion" maxOccurs="unbounded">
                    <xs:complexType>
                    
                        <xs:sequence>
                            <xs:element name="categoria">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Alta"/>
                                        <xs:enumeration value="Media"/>
                                        <xs:enumeration value="Baixa"/>
                                    </xs:restriction>   
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="cantidad" >
                                <xs:simpleType>
                                    <xs:restriction base="xs:positiveInteger">
                                        <xs:minInclusive value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="descripcion" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" use="required" type="xs:positiveInteger"/>
                        <xs:attribute name="tipo" use="required" type="tipo_agrupacion"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="tipo_agrupacion">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Normal"/>
            <xs:enumeration value="Especial"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== h3rm3x/DAM/LMSGI/UD4/EXAMEN_XSD/EX_7/ejercicio7.xml
<?xml version="1.0" encoding="UTF-8"?>
<datos
  xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
  xs:noNamespaceSchemaLocation="ejercicio7.xsd">
  <agrupacion id="1" tipo="Normal">
    <categoria>Alta</categoria>
    <cantidad>15</cantidad>
    <descripcion>Primera agrupación</descripcion>
  </agrupacion>
  <agrupacion id="2" tipo="Especial">
    <categoria>Media</categoria>
    <cantidad>8</cantidad>
    <descripcion>Segunda agrupación</descripcion>
  </agrupacion>
</datos>
