<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empresa [
    <!ELEMENT empresa (compra*, venta*)>
    <!ELEMENT compra (id, titulos, fecha)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT venta (titulos, unidades_totales, importe, entregado?)>
    <!ELEMENT titulos (titulo+)>
    <!ELEMENT titulo (#PCDATA)>
    <!ATTLIST titulo unidades CDATA #REQUIRED>
    <!ELEMENT fecha (dia, mes, año)>
    <!ELEMENT dia (#PCDATA)>
    <!ELEMENT mes (#PCDATA)>
    <!ELEMENT año (#PCDATA)>
    <!ELEMENT unidades_totales (#PCDATA)>
    <!ELEMENT importe (#PCDATA)>
    <!ATTLIST importe moneda CDATA #REQUIRED>
    <!ELEMENT entregado (#PCDATA)>
]>
<empresa>
    <compra>
        <id>1</id>
        <titulos>
            <titulo unidades="1">Libro 1 </titulo>
            <titulo unidades="3">Libro 2 </titulo>  
        </titulos>
        <fecha >
            <dia> 24</dia>
            <mes> 10</mes>
            <año> 2024</año>    
        </fecha>

    </compra>

    <venta >
        <titulos>
            <titulo unidades="2">Libro 1 </titulo>
            <titulo unidades="4">Libro 3 </titulo>  
        </titulos>
        <unidades_totales>6</unidades_totales>
        <importe moneda="€">65</importe>
        <entregado>Si</entregado>
    </venta>

    <venta >
        <titulos>
            <titulo unidades="1">Libro 2 </titulo>
            <titulo unidades="2">Libro 3 </titulo>  
        </titulos>
        <unidades_totales>3</unidades_totales>
        <importe moneda="$">48</importe>
    </venta>    


</empresa>