<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE comanda [
    <!ELEMENT comanda (tractor*)>
    <!ELEMENT tractor (componente+)>
    <!ELEMENT componente (fecha_entrega, peso, numero_serie)>
    <!ATTLIST componente fabricante CDATA #REQUIRED>
    <!ATTLIST componente fragil CDATA #REQUIRED>
    <!ELEMENT fecha_entrega (dia?, mes, año)>
    <!ELEMENT dia (#PCDATA)>
    <!ELEMENT mes (#PCDATA)>
    <!ELEMENT año (#PCDATA)>
    <!ELEMENT peso (#PCDATA)>
    <!ELEMENT numero_serie (#PCDATA)>

]>
<comanda>
    <tractor>
        <componente fabricante="John Deere" fragil="no">
            <fecha_entrega>  
                <dia> 13</dia>
                <mes> 02</mes>
                <año> 2025</año>
            </fecha_entrega>
            <peso>2000</peso>
            <numero_serie>123478</numero_serie>
        </componente>
        <componente fabricante="Mitsubishi" fragil="si">
            <fecha_entrega>  
                <mes> 02</mes>
                <año> 2025</año>
            </fecha_entrega>
            <peso>2400</peso>
            <numero_serie>14578</numero_serie>
        </componente>
        <componente fabricante="John Deere" fragil="no">
            <fecha_entrega>  
                <mes> 03</mes>
                <año> 2025</año>
            </fecha_entrega>
            <peso>1000</peso>
            <numero_serie>456472</numero_serie>
        </componente>
    </tractor>
    <tractor>
        <componente fabricante="John Deere" fragil="si">
            <fecha_entrega>  
                <dia> 21</dia>
                <mes> 07</mes>
                <año> 2025</año>
            </fecha_entrega>
            <peso>2400</peso>
            <numero_serie>478121</numero_serie>
        </componente>
        <componente fabricante="Wolkswagen" fragil="si">
            <fecha_entrega>  
                <mes> 03</mes>
                <año> 2025</año>
            </fecha_entrega>
            <peso>2700</peso>
            <numero_serie>214103</numero_serie>
        </componente>
        <componente fabricante="John Deere" fragil="no">
            <fecha_entrega>  
                <mes> 05</mes>
                <año> 2025</año>
            </fecha_entrega>
            <peso>1400</peso>
            <numero_serie>245689</numero_serie>
        </componente>
    </tractor>
</comanda>